# Site settings
title: Jhamut.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on web design, wushu and baking.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jhamut.com" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false